default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  pool: 5

development:
  <<: *default
  database: pizza-analytics_development

test:
  <<: *default
  database: pizza-analytics_test
