default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  pool: 5

development:
  <<: *default
  database: pizza_analytics_development
  # database: pizza_analytics_development_4

test:
  <<: *default
  database: pizza_analytics_test
